### ISSUE TITLE
自动开始下一把存在点不进去的问题

### ISSUE THREAD

**Issue by SamleTT** [latorc/MahjongCopilot#14]
会出现点开某个间 里面没有场的选项，然后卡死一直

**Comment by SamleTT** [comment]
![Uploading {3CA385CC-DD58-4f1f-870B-24E20461AADA}.png…]()


如图

**Comment by SamleTT** [comment]
![Uploading 4aa583e9bd1a4e11dd1f3ac628c4b76f.png…]()

**Comment by latorc** [comment]
0.5.3 版本还有这个状况吗？

**Comment by latorc** [comment]
检查一下是否浏览器缩放了。
