### ISSUE TITLE
Request for GUI Compatibility Enhancement and Dynamic Scaling for Different Resolutions

### ISSUE THREAD

**Issue by sdkfuck** [latorc/MahjongCopilot#16]
The current GUI is not compatible with 2K resolution, leading to incomplete text display. It would be greatly appreciated if the GUI could support dynamic scaling with different zoom ratios for various resolutions, ensuring adaptability across different display settings.

![image](https://github.com/latorc/MahjongCopilot/assets/86214484/dbbf2f9d-0431-438b-9f56-cee76d2f8653)

**Comment by latorc** [comment]
Please check 0.5.3 and see if it is fixed

**Comment by sdkfuck** [comment]
I tested it and found that I need to enlarge the window to see the full view. If possible, I hope the GUI can be adjusted according to the computer screen resolution and scaling ratio.thank u.(*￣︶￣)
