### ISSUE TITLE
提示GUI更换字体

### ISSUE THREAD

**Issue by Zxis233** [latorc/MahjongCopilot#34]
看到readme中的GUI可以正常显示麻将的彩色Emoji，请问使用的是哪一款字体？
是否可以在Python中进行指定？

**Comment by latorc** [comment]
GUI 上暂时只能黑白哦
至少windows是这样

**Comment by Zxis233** [comment]
> GUI 上暂时只能黑白哦 至少windows是这样

请问其他操作系统是否可以显示彩色图标？如果可以的话，可以告知字体的名称吗？

**Comment by latorc** [comment]
就是这个字体。只是 tkinter不能显示彩色。 mac上没试过
