### ISSUE TITLE
考虑在 README 中让用户手动安装 mitmproxy 以及证书

### ISSUE THREAD

**Issue by BoYanZh** [latorc/MahjongCopilot#40]
保证根证书生成的唯一性

**Comment by latorc** [comment]
证书使用 mitm_config 中的证书，只生成一次

**Comment by BoYanZh** [comment]
我觉得可以在 README 里提示让对安全有需求的用户自行安装 mitmproxy 后用 ~/.mitmproxy 中的内容替换 mitm_config

根据 https://docs.mitmproxy.org/stable/concepts-certificates/，最好每个用户生成一个唯一的证书

> For security reasons, the mitmproxy CA is generated uniquely on the first start and is not shared between mitmproxy installations on different devices. This makes sure that other mitmproxy users cannot intercept your traffic.

**Comment by latorc** [comment]
Copilot启动的时候，第一次调用mitm，mitm会自动生成随机证书，放到mitm_config目录中。这应该没错吧？

**Comment by BoYanZh** [comment]
我的问题 直接跑 mitm.py 没看清结果
