### ISSUE TITLE
开启自动打牌时超时切换自动模式

### ISSUE THREAD

**Issue by kotoricon** [latorc/MahjongCopilot#41]
不知道是不是必须一直焦点在游戏里造成的，反正如果时不时切出去干点别的忘了切回去再回去看的时候就显示变成自动模式了，反正X+20秒肯定是没了

**Comment by fon11731** [comment]
没有吖

**Comment by kotoricon** [comment]
![20240501000123](https://github.com/latorc/MahjongCopilot/assets/8659834/7ca8e27e-57de-44e2-bf90-e807b18a7d31)
RT

**Comment by kotoricon** [comment]
刚说完不到5分钟就遇到第二次。。
![20240501000533](https://github.com/latorc/MahjongCopilot/assets/8659834/bef71527-de37-43ba-b470-c4162364c980)

**Comment by latorc** [comment]
可能是窗口没有在前台造成的？

**Comment by haoyun0** [comment]
焦点不需要一直在游戏，但是不能最小化，可以被别的窗口盖着，windows用多个桌面就很方便

**Comment by latorc** [comment]
网页端有一定的游戏挂机检测的，网页不要最小化一般没问题。
