### ISSUE TITLE
MITM证书导入成功但程序未识别

### ISSUE THREAD

**Issue by Alicesaku** [latorc/MahjongCopilot#45]
已尝试管理员身份运行MahjongCopilot.exe和手动安装mitmproxy-ca-cert.cer到本地计算机受信任的根证书颁发机构，证书显示导入成功，但打开Copilot右下角仍是红叉？请问是证书未能正确安装吗？

**Comment by latorc** [comment]
安装的时候，是否为”计算机“安装
