### ISSUE TITLE
存在一直点牌不出牌的情况，直到超时

### ISSUE THREAD

**Issue by foreverliver** [latorc/MahjongCopilot#9]
存在一直点牌不出牌的情况，直到超时

**Comment by latorc** [comment]
是东家一巡，理牌还没结束的时候？ 这个情况修复了。

另外是否有点击牌出不去的情况？

**Comment by foreverliver** [comment]
就是0.4.3，把鼠标随机调成0，然后开一局友人局就能看到，点牌不出的情况，每次拖个5-10s，两次就超时了，然后只能超时摸切

**Comment by foreverliver** [comment]
测了，0.4.4还是存在，在牌升起但是不出牌的情况，直到时间结束

**Comment by foreverliver** [comment]
0.3.0b那个版本没这种情况，0.3.0b只有立直牌点炮的bug

**Comment by wipe6207** [comment]
最新版仍然有这种情况

**Comment by SamleTT** [comment]
+1  点牌但是出不出去，一直在那重复点

**Comment by latorc** [comment]
0.4.5 是否有解决？

**Comment by foreverliver** [comment]
拖动出牌后有所改善，虽然有时还是超时，但是剩余时间大于10s,没有超时摸切情况

**Comment by latorc** [comment]
可以试一下，设置里把“随机移动”关掉，这样不会拖动，只是点击。 
只是点击是否能顺利出牌？

**Comment by wipe6207** [comment]
点击出牌仍然有打不出去牌的情况，拖动出牌没问题

**Comment by latorc** [comment]
暂时以鼠标拖动出牌来解决
